sm_cpp: main.cpp
	g++ -o sm_cpp main.cpp

run-cpp: sm_cpp
	./sm_cpp

sm_rs: main.rs
	rustc -o sm_rs main.rs

run-rs: sm_rs
	./sm_rs

sm_rs1: main1.rs
	rustc -o sm_rs1 main1.rs

run-rs1: sm_rs1
	./sm_rs1
