iter_cpp: main.cpp
	g++ -o iter_cpp main.cpp

run-cpp: iter_cpp
	./iter_cpp

iter_rs: main.rs
	rustc -o iter_rs main.rs

run-rs: iter_rs
	./iter_rs

iter_rs1: main1.rs
	rustc -o iter_rs1 main1.rs

run-rs1: iter_rs1
	./iter_rs1

iter_rs2: main2.rs
	rustc -o iter_rs2 main2.rs

run-rs2: iter_rs2
	./iter_rs2
