struct_rs: main.rs
	rustc -o struct_rs main.rs

run-rs: struct_rs
	./struct_rs

struct_rs1: main1.rs
	rustc -o struct_rs1 main1.rs

run-rs1: struct_rs1
	./struct_rs1

struct_rs2: main2.rs
	rustc -o struct_rs2 main2.rs

run-rs2: struct_rs2
	./struct_rs2

struct_rs3: main3.rs
	rustc -o struct_rs3 main3.rs

run-rs3: struct_rs3
	./struct_rs3

struct_rs4: main4.rs
	rustc -o struct_rs4 main4.rs

run-rs4: struct_rs4
	./struct_rs4

struct_rs5: main5.rs
	rustc -o struct_rs5 main5.rs

run-rs5: struct_rs5
	./struct_rs5

struct_rs6: main6.rs
	rustc -o struct_rs6 main6.rs

run-rs6: struct_rs6
	./struct_rs6

