dan_cpp: main.cpp
	g++ -o dan_cpp main.cpp

run-cpp: dan_cpp
	./dan_cpp

dan_rs: main.rs
	rustc -o dan_rs main.rs

run-rs: dan_rs
	./dan_rs

dan_rs1: main1.rs
	rustc -o dan_rs1 main1.rs

run-rs1: dan_rs1
	./dan_rs1

dan_rs2: main2.rs
	rustc -o dan_rs2 main2.rs

run-rs2: dan_rs2
	./dan_rs2

dan_rs3: main3.rs
	rustc -o dan_rs3 main3.rs

run-rs3: dan_rs3
	./dan_rs3

